#!/usr/bin/python3
# -*- coding: utf-8 -*-
#
# Global symbols from file empty.txt
# Autogenerated file, do not modify!
#
class globalSymbols():

   symbols= {
   }
   @staticmethod
   def get(name):
      if name[0]=='=':
         name=name[1:]
      if name in globalSymbols.symbols.keys():
         return globalSymbols.symbols[name]
      else:
         return None

